name: Release Deployment
on:
  release:
    types:
      - created
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        name: Checkout

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          server-id: nexus
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Deploy Release
        run: mvn clean --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}